name: azure_blobstorage_utils

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.9
  - setuptools
  - autopep8
  - pytest
  - ipykernel
  - pyyaml
  - pip:
      - azure-storage-blob
      - aiohttp
      - asyncio
      - pandas
      - openpyxl
      - opencv-python
