name: azure_blobstorage_utils

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7.6
  - setuptools
  - autopep8
  - pytest
  - ipykernel
  - pyyaml
  - pip:
    - azure-storage-blob
    - pandas
    - openpyxl
    - opencv-python
