site_name: Azure Blob Storage Utils
repo_url: https://github.com/OpenValue/azure_blobstorage_utils
repo_name: OpenValue/azure_blobstorage_utils
edit_uri: "" #disables edit button
nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
          - Basic Usage: basic_usage.md
          - Extended Usage: extended_usage.md
    - About: about.md
theme:
    name: material
    icon:
      repo: fontawesome/brands/github-alt
    features:
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: teal
        accent: amber
        toggle:
          icon: material/lightbulb
          name: Switch to light mode
      - scheme: slate
        primary: teal
        accent: amber
        toggle:
          icon: material/lightbulb-outline
          name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          #setup_commands:
          #  - import sys
          #  - sys.path.append("src")
          rendering:
            show_source: false
            merge_init_into_class: true
            separate_signature: true
            docstring_options:
              ignore_init_summary: yes
          watch:
            - src/azure_blobstorage_utils
