site_name: Azure Blob Storage Utils
repo_url: https://github.com/OpenValue/azure_blobstorage_utils
repo_name: OpenValue/azure_blobstorage_utils
edit_uri: "" #disables edit button
nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
          - Basic Usage: basic_usage.md
          - Extended Usage: extended_usage.md
    - About: about.md
theme:
    name: material
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - search.highlight
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters: [ "!^_" ]
          rendering:
            show_source: false
            merge_init_into_class: True
